### PR TITLE
Divide and conquer

### PR DESCRIPTION
**Pull request by jonathanstanley**
This isn't polished at all, but most of the heavy lifting is done.

I think this gets us 90% towards the goal of issue https://github.com/joshtronic/php-googleplaces/issues/5

### CODE REVIEW

**Comment by Surt** [comment]
Hi, any news about this feature? is it possible to use it? seems like a great addition and I'm actually in need of it.

**Comment by joshtronic** [comment]
ACK That's no good @Surt ... feel free to debug and resolve if you have a moment. I'll try to make some time this week to see what may be happening. @bristweb feel free to check into it if you have time as well.

Thanks!

**Comment by bristweb** [comment]
Hmm I took a look at some comments I left here:
https://github.com/joshtronic/php-googleplaces/issues/5#issuecomment-37577261

It looks like you need to set the radius and subradius to an integer.  ex:
`$radius = 40000;
$subradius = 20000;`

The script shouldn't alter the request other than simply creating a bunch of smaller requests.  Does the request work if you do not set the subradius?

Other than that... it's been a little while since I've looked at this....

**Comment by Surt** [comment]
It works like a charm. It was my fault due to the use of ```$google_places->rankby   = 'distance';```
didn't have the time to check it deeper but getting rid of it it works right.

**Comment by joshtronic** [comment]
@Surt glad it worked out! Should probably add something in there to raise an exception or ignore the flag if it's there. Appreciate you bringing this to my attention!

**Pull request merged**
